### ISSUE TITLE
Border is clipped if 'W' is first letter in word.

### ISSUE THREAD

**Issue by mattdewey** [simonwhitaker/memerbot#3]
If the test on either top or bottom begins with the letter 'W' the border remains a straight vertical line and is clipped instead of angling to the 'W' like it does at the end of a word.
![screen shot 2016-07-03 at 8 46 25 am](https://cloud.githubusercontent.com/assets/19596210/16546288/d165e1dc-40fa-11e6-9a67-12af9edc6e33.png)

**Comment by simonwhitaker** [comment]
eb9e2cf seems to have fixed this one
